package gui;

import java.io.IOException;

import javax.swing.JOptionPane;

import com.formdev.flatlaf.FlatLightLaf;

import model.Cart;
import model.Item;
import model.ItemNode;
import model.Stock;

/**
 *
 * @author robert.fisch
 */
public class MainFrame extends javax.swing.JFrame {

	private Stock stock = new Stock();
	private Cart cart = new Cart();

	/**
	 * Creates new form MainFrame
	 */
	public MainFrame() {
		FlatLightLaf.setup(); // given

		initComponents();

		try {
			stock.loadFromCsv("books_stock.csv");
		} catch (IOException e) {
			JOptionPane.showMessageDialog(this, e);
		}
		stockList.setListData(stock.toArray());
//		System.err.println(Arrays.toString(stock.toArray()));
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify
	 * this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jSplitPane1 = new javax.swing.JSplitPane();
		cartPanel = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		cartList = new javax.swing.JList();
		jLabel5 = new javax.swing.JLabel();
		totalLabel = new javax.swing.JLabel();
		stockPanel = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		searchTextField = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		countTextField = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		addButton = new javax.swing.JButton();
		jScrollPane3 = new javax.swing.JScrollPane();
		stockList = new javax.swing.JList();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Library Shop");
		setPreferredSize(new java.awt.Dimension(800, 600));

		jSplitPane1.setDividerLocation(400);
		jSplitPane1.setDividerSize(0);
		jSplitPane1.setResizeWeight(0.5);

		cartPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Cart"));
		cartPanel.setPreferredSize(new java.awt.Dimension(300, 457));

		cartList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
		jScrollPane1.setViewportView(cartList);

		jLabel5.setText("Total = ");

		totalLabel.setText("0 €");

		javax.swing.GroupLayout cartPanelLayout = new javax.swing.GroupLayout(cartPanel);
		cartPanel.setLayout(cartPanelLayout);
		cartPanelLayout
				.setHorizontalGroup(cartPanelLayout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(cartPanelLayout
								.createSequentialGroup()
								.addContainerGap()
								.addGroup(cartPanelLayout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
										.addGroup(cartPanelLayout
												.createSequentialGroup()
												.addComponent(jLabel5,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														51,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(totalLabel,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)))
								.addContainerGap()));
		cartPanelLayout
				.setVerticalGroup(cartPanelLayout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(cartPanelLayout
								.createSequentialGroup()
								.addContainerGap()
								.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(cartPanelLayout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel5)
										.addComponent(totalLabel))
								.addContainerGap()));

		jSplitPane1.setRightComponent(cartPanel);

		stockPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Stock"));

		jLabel1.setText("Search");

		searchTextField.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyReleased(java.awt.event.KeyEvent evt) {
				searchTextFieldKeyReleased(evt);
			}
		});

		jLabel2.setText("Add");

		countTextField.setText("1");

		jLabel3.setText("of the selected items to the cart.");

		addButton.setText("Add");
		addButton.setEnabled(false);
		addButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				addButtonActionPerformed(evt);
			}
		});

		stockList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
		stockList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
			public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
				stockListValueChanged(evt);
			}
		});
		jScrollPane3.setViewportView(stockList);

		javax.swing.GroupLayout stockPanelLayout = new javax.swing.GroupLayout(stockPanel);
		stockPanel.setLayout(stockPanelLayout);
		stockPanelLayout
				.setHorizontalGroup(stockPanelLayout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(stockPanelLayout
								.createSequentialGroup()
								.addContainerGap()
								.addGroup(stockPanelLayout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(stockPanelLayout
												.createSequentialGroup()
												.addComponent(jLabel2,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														31,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(countTextField,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														71,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(jLabel3,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														181,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(addButton)
												.addGap(0, 12, Short.MAX_VALUE))
										.addGroup(stockPanelLayout
												.createSequentialGroup()
												.addGap(4, 4, 4)
												.addComponent(jLabel1,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														43,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(searchTextField))
										.addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING))
								.addContainerGap()));
		stockPanelLayout
				.setVerticalGroup(stockPanelLayout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(stockPanelLayout
								.createSequentialGroup()
								.addContainerGap()
								.addGroup(stockPanelLayout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel1)
										.addComponent(searchTextField,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(stockPanelLayout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel2)
										.addComponent(countTextField,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabel3)
										.addComponent(addButton))
								.addContainerGap()));

		jSplitPane1.setLeftComponent(stockPanel);

		getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void searchTextFieldKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_searchTextFieldKeyReleased

		if (searchTextField.getText() == null || searchTextField.getText().isBlank()) {
			stockList.setListData(stock.toArray());
		} else {
			stockList.setListData(stock.searchStartWith(searchTextField.getText()).toArray(ItemNode[]::new));
		}

	}// GEN-LAST:event_searchTextFieldKeyReleased

	private void stockListValueChanged(javax.swing.event.ListSelectionEvent evt) {// GEN-FIRST:event_stockListValueChanged
		addButton.setEnabled(stockList.getSelectedIndex() >= 0);
		countTextField.setText("1");
		countTextField.selectAll();
		countTextField.requestFocus();
	}// GEN-LAST:event_stockListValueChanged

	private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_addButtonActionPerformed
		if (stockList.getSelectedIndex() < 0) {
			return;
		}

		try {
			final int idx = stockList.getSelectedIndex();
			final Item it = ((ItemNode) stockList.getSelectedValue()).getItem();
			cart.addOrIncrementCount(it, stock.removeOrDecrement(it, Integer.parseInt(countTextField.getText())));
			final ItemNode[] arr = cart.toArray();
			cartList.setListData(arr);
			searchTextFieldKeyReleased(null);
			if (idx <= arr.length && idx >= 0)
				stockList.setSelectedIndex(idx);
		} catch (Exception e) {
			e.printStackTrace();
			JOptionPane.showMessageDialog(this, e);
		}

		totalLabel.setText(cart.getTotal() + " €");

	}// GEN-LAST:event_addButtonActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel. For
		 * details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainFrame().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton addButton;
	private javax.swing.JList cartList;
	private javax.swing.JPanel cartPanel;
	private javax.swing.JTextField countTextField;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane3;
	private javax.swing.JSplitPane jSplitPane1;
	private javax.swing.JTextField searchTextField;
	private javax.swing.JList stockList;
	private javax.swing.JPanel stockPanel;
	private javax.swing.JLabel totalLabel;
	// End of variables declaration//GEN-END:variables
}